var Entities = {
	version:"1.3.168",
	enableXmlStdReplacement:true,
	table: [
		
		{symbol:" ", entity:{name:"nbsp", code:160}, description:"неразрывный пробел", unicode:"U+00A0", iso:"ISOnum"},
		{symbol:"¡", entity:{name:"iexcl", code:161}, description:"перевернутый восклицательный знак", unicode:"U+00A1", iso:"ISOnum"},
		{symbol:"¢", entity:{name:"cent", code:162}, description:"цент", unicode:"U+00A2", iso:"ISOnum"},
		{symbol:"£", entity:{name:"pound", code:163}, description:"фунт стерлингов", unicode:"U+00A3", iso:"ISOnum"},
		{symbol:"¤", entity:{name:"curren", code:164}, description:"денежная единица", unicode:"U+00A4", iso:"ISOnum"},
		{symbol:"¥", entity:{name:"yen", code:165}, description:"иена или юань", unicode:"U+00A5", iso:"ISOnum"},
		{symbol:"¦", entity:{name:"brvbar", code:166}, description:"разорванная вертикальная черта", unicode:"U+00A6", iso:"ISOnum"},
		{symbol:"§", entity:{name:"sect", code:167}, description:"параграф", unicode:"U+00A7", iso:"ISOnum"},
		{symbol:"¨", entity:{name:"uml", code:168}, description:"diaeresis = spacing diaeresis", unicode:"U+00A8", iso:"ISOdia"},
		{symbol:"©", entity:{name:"copy", code:169}, description:"знак copyright", unicode:"U+00A9", iso:"ISOnum"},
		{symbol:"ª", entity:{name:"ordf", code:170}, description:"feminine ordinal indicator", unicode:"U+00AA", iso:"ISOnum"},
		{symbol:"«", entity:{name:"laquo", code:171}, description:"левая двойная угловая скобка", unicode:"U+00AB", iso:"ISOnum"},
		{symbol:"¬", entity:{name:"not", code:172}, description:"знак отрицания", unicode:"U+00AC", iso:"ISOnum"},
		{symbol:"­", entity:{name:"shy", code:173}, description:"место возможного переноса", unicode:"U+00AD", iso:"ISOnum"},
		{symbol:"®", entity:{name:"reg", code:174}, description:"знак зарегистрированной торговой марки", unicode:"U+00AE", iso:"ISOnum"},
		{symbol:"¯", entity:{name:"macr", code:175}, description:"macron = spacing macron = overline = APL overbar", unicode:"U+00AF", iso:"ISOdia"},
		{symbol:"°", entity:{name:"deg", code:176}, description:"градус", unicode:"U+00B0", iso:"ISOnum"},
		{symbol:"±", entity:{name:"plusmn", code:177}, description:"плюс-минус", unicode:"U+00B1", iso:"ISOnum"},
		{symbol:"²", entity:{name:"sup2", code:178}, description:"верхний индекс 'два' – 'квадрат'", unicode:"U+00B2", iso:"ISOnum"},
		{symbol:"³", entity:{name:"sup3", code:179}, description:"верхний индекс 'три' – 'куб'", unicode:"U+00B3", iso:"ISOnum"},
		{symbol:"´", entity:{name:"acute", code:180}, description:"acute accent = spacing acute", unicode:"U+00B4", iso:"ISOdia"},
		{symbol:"µ", entity:{name:"micro", code:181}, description:"микро", unicode:"U+00B5", iso:"ISOnum"},
		{symbol:"¶", entity:{name:"para", code:182}, description:"pilcrow sign = paragraph sign", unicode:"U+00B6", iso:"ISOnum"},
		{symbol:"·", entity:{name:"middot", code:183}, description:"middle dot = Georgian comma = Greek middle dot", unicode:"U+00B7", iso:"ISOnum"},
		{symbol:"¸", entity:{name:"cedil", code:184}, description:"cedilla = spacing cedilla", unicode:"U+00B8", iso:"ISOdia"},
		{symbol:"¹", entity:{name:"sup1", code:185}, description:"верхний индекс 'один'", unicode:"U+00B9", iso:"ISOnum"},
		{symbol:"º", entity:{name:"ordm", code:186}, description:"masculine ordinal indicator", unicode:"U+00BA", iso:"ISOnum"},
		{symbol:"»", entity:{name:"raquo", code:187}, description:"правая двойная угловая скобка", unicode:"U+00BB", iso:"ISOnum"},
		{symbol:"¼", entity:{name:"frac14", code:188}, description:"дробь – одна четверть", unicode:"U+00BC", iso:"ISOnum"},
		{symbol:"½", entity:{name:"frac12", code:189}, description:"дробь – одна вторая", unicode:"U+00BD", iso:"ISOnum"},
		{symbol:"¾", entity:{name:"frac34", code:190}, description:"дробь – три четверти", unicode:"U+00BE", iso:"ISOnum"},
		{symbol:"¿", entity:{name:"iquest", code:191}, description:"перевернутый вопросительный знак", unicode:"U+00BF", iso:"ISOnum"},
		{symbol:"À", entity:{name:"Agrave", code:192}, description:"latin capital letter A with grave = latin capital letter A grave", unicode:"U+00C0", iso:"ISOlat1"},
		{symbol:"Á", entity:{name:"Aacute", code:193}, description:"latin capital letter A with acute", unicode:"U+00C1", iso:"ISOlat1"},
		{symbol:"Â", entity:{name:"Acirc", code:194}, description:"latin capital letter A with circumflex", unicode:"U+00C2", iso:"ISOlat1"},
		{symbol:"Ã", entity:{name:"Atilde", code:195}, description:"latin capital letter A with tilde", unicode:"U+00C3", iso:"ISOlat1"},
		{symbol:"Ä", entity:{name:"Auml", code:196}, description:"latin capital letter A with diaeresis", unicode:"U+00C4", iso:"ISOlat1"},
		{symbol:"Å", entity:{name:"Aring", code:197}, description:"latin capital letter A with ring above = latin capital letter A ring", unicode:"U+00C5", iso:"ISOlat1"},
		{symbol:"Æ", entity:{name:"AElig", code:198}, description:"latin capital letter AE = latin capital ligature AE", unicode:"U+00C6", iso:"ISOlat1"},
		{symbol:"Ç", entity:{name:"Ccedil", code:199}, description:"latin capital letter C with cedilla", unicode:"U+00C7", iso:"ISOlat1"},
		{symbol:"È", entity:{name:"Egrave", code:200}, description:"latin capital letter E with grave", unicode:"U+00C8", iso:"ISOlat1"},
		{symbol:"É", entity:{name:"Eacute", code:201}, description:"latin capital letter E with acute", unicode:"U+00C9", iso:"ISOlat1"},
		{symbol:"Ê", entity:{name:"Ecirc", code:202}, description:"latin capital letter E with circumflex", unicode:"U+00CA", iso:"ISOlat1"},
		{symbol:"Ë", entity:{name:"Euml", code:203}, description:"latin capital letter E with diaeresis", unicode:"U+00CB", iso:"ISOlat1"},
		{symbol:"Ì", entity:{name:"Igrave", code:204}, description:"latin capital letter I with grave", unicode:"U+00CC", iso:"ISOlat1"},
		{symbol:"Í", entity:{name:"Iacute", code:205}, description:"latin capital letter I with acute", unicode:"U+00CD", iso:"ISOlat1"},
		{symbol:"Î", entity:{name:"Icirc", code:206}, description:"latin capital letter I with circumflex", unicode:"U+00CE", iso:"ISOlat1"},
		{symbol:"Ï", entity:{name:"Iuml", code:207}, description:"latin capital letter I with diaeresis", unicode:"U+00CF", iso:"ISOlat1"},
		{symbol:"Ð", entity:{name:"ETH", code:208}, description:"latin capital letter ETH", unicode:"U+00D0", iso:"ISOlat1"},
		{symbol:"Ñ", entity:{name:"Ntilde", code:209}, description:"latin capital letter N with tilde", unicode:"U+00D1", iso:"ISOlat1"},
		{symbol:"Ò", entity:{name:"Ograve", code:210}, description:"latin capital letter O with grave", unicode:"U+00D2", iso:"ISOlat1"},
		{symbol:"Ó", entity:{name:"Oacute", code:211}, description:"latin capital letter O with acute", unicode:"U+00D3", iso:"ISOlat1"},
		{symbol:"Ô", entity:{name:"Ocirc", code:212}, description:"latin capital letter O with circumflex", unicode:"U+00D4", iso:"ISOlat1"},
		{symbol:"Õ", entity:{name:"Otilde", code:213}, description:"latin capital letter O with tilde", unicode:"U+00D5", iso:"ISOlat1"},
		{symbol:"Ö", entity:{name:"Ouml", code:214}, description:"latin capital letter O with diaeresis", unicode:"U+00D6", iso:"ISOlat1"},
		{symbol:"×", entity:{name:"times", code:215}, description:"знак умножения", unicode:"U+00D7", iso:"ISOnum"},
		{symbol:"Ø", entity:{name:"Oslash", code:216}, description:"latin capital letter O with stroke = latin capital letter O slash", unicode:"U+00D8", iso:"ISOlat1"},
		{symbol:"Ù", entity:{name:"Ugrave", code:217}, description:"latin capital letter U with grave", unicode:"U+00D9", iso:"ISOlat1"},
		{symbol:"Ú", entity:{name:"Uacute", code:218}, description:"latin capital letter U with acute", unicode:"U+00DA", iso:"ISOlat1"},
		{symbol:"Û", entity:{name:"Ucirc", code:219}, description:"latin capital letter U with circumflex", unicode:"U+00DB", iso:"ISOlat1"},
		{symbol:"Ü", entity:{name:"Uuml", code:220}, description:"latin capital letter U with diaeresis", unicode:"U+00DC", iso:"ISOlat1"},
		{symbol:"Ý", entity:{name:"Yacute", code:221}, description:"latin capital letter Y with acute", unicode:"U+00DD", iso:"ISOlat1"},
		{symbol:"Þ", entity:{name:"THORN", code:222}, description:"latin capital letter THORN", unicode:"U+00DE", iso:"ISOlat1"},
		{symbol:"ß", entity:{name:"szlig", code:223}, description:"latin small letter sharp s = ess-zed", unicode:"U+00DF", iso:"ISOlat1"},
		{symbol:"à", entity:{name:"agrave", code:224}, description:"latin small letter a with grave = latin small letter a grave", unicode:"U+00E0", iso:"ISOlat1"},
		{symbol:"á", entity:{name:"aacute", code:225}, description:"latin small letter a with acute", unicode:"U+00E1", iso:"ISOlat1"},
		{symbol:"â", entity:{name:"acirc", code:226}, description:"latin small letter a with circumflex", unicode:"U+00E2", iso:"ISOlat1"},
		{symbol:"ã", entity:{name:"atilde", code:227}, description:"latin small letter a with tilde", unicode:"U+00E3", iso:"ISOlat1"},
		{symbol:"ä", entity:{name:"auml", code:228}, description:"latin small letter a with diaeresis", unicode:"U+00E4", iso:"ISOlat1"},
		{symbol:"å", entity:{name:"aring", code:229}, description:"latin small letter a with ring above = latin small letter a ring", unicode:"U+00E5", iso:"ISOlat1"},
		{symbol:"æ", entity:{name:"aelig", code:230}, description:"latin small letter ae = latin small ligature ae", unicode:"U+00E6", iso:"ISOlat1"},
		{symbol:"ç", entity:{name:"ccedil", code:231}, description:"latin small letter c with cedilla", unicode:"U+00E7", iso:"ISOlat1"},
		{symbol:"è", entity:{name:"egrave", code:232}, description:"latin small letter e with grave", unicode:"U+00E8", iso:"ISOlat1"},
		{symbol:"é", entity:{name:"eacute", code:233}, description:"latin small letter e with acute", unicode:"U+00E9", iso:"ISOlat1"},
		{symbol:"ê", entity:{name:"ecirc", code:234}, description:"latin small letter e with circumflex", unicode:"U+00EA", iso:"ISOlat1"},
		{symbol:"ë", entity:{name:"euml", code:235}, description:"latin small letter e with diaeresis", unicode:"U+00EB", iso:"ISOlat1"},
		{symbol:"ì", entity:{name:"igrave", code:236}, description:"latin small letter i with grave", unicode:"U+00EC", iso:"ISOlat1"},
		{symbol:"í", entity:{name:"iacute", code:237}, description:"latin small letter i with acute", unicode:"U+00ED", iso:"ISOlat1"},
		{symbol:"î", entity:{name:"icirc", code:238}, description:"latin small letter i with circumflex", unicode:"U+00EE", iso:"ISOlat1"},
		{symbol:"ï", entity:{name:"iuml", code:239}, description:"latin small letter i with diaeresis", unicode:"U+00EF", iso:"ISOlat1"},
		{symbol:"ð", entity:{name:"eth", code:240}, description:"latin small letter eth", unicode:"U+00F0", iso:"ISOlat1"},
		{symbol:"ñ", entity:{name:"ntilde", code:241}, description:"latin small letter n with tilde", unicode:"U+00F1", iso:"ISOlat1"},
		{symbol:"ò", entity:{name:"ograve", code:242}, description:"latin small letter o with grave", unicode:"U+00F2", iso:"ISOlat1"},
		{symbol:"ó", entity:{name:"oacute", code:243}, description:"latin small letter o with acute", unicode:"U+00F3", iso:"ISOlat1"},
		{symbol:"ô", entity:{name:"ocirc", code:244}, description:"latin small letter o with circumflex", unicode:"U+00F4", iso:"ISOlat1"},
		{symbol:"õ", entity:{name:"otilde", code:245}, description:"latin small letter o with tilde", unicode:"U+00F5", iso:"ISOlat1"},
		{symbol:"ö", entity:{name:"ouml", code:246}, description:"latin small letter o with diaeresis", unicode:"U+00F6", iso:"ISOlat1"},
		{symbol:"÷", entity:{name:"divide", code:247}, description:"знак деления", unicode:"U+00F7", iso:"ISOnum"},
		{symbol:"ø", entity:{name:"oslash", code:248}, description:"latin small letter o with stroke, = latin small letter o slash", unicode:"U+00F8", iso:"ISOlat1"},
		{symbol:"ù", entity:{name:"ugrave", code:249}, description:"latin small letter u with grave", unicode:"U+00F9", iso:"ISOlat1"},
		{symbol:"ú", entity:{name:"uacute", code:250}, description:"latin small letter u with acute", unicode:"U+00FA", iso:"ISOlat1"},
		{symbol:"û", entity:{name:"ucirc", code:251}, description:"latin small letter u with circumflex", unicode:"U+00FB", iso:"ISOlat1"},
		{symbol:"ü", entity:{name:"uuml", code:252}, description:"latin small letter u with diaeresis", unicode:"U+00FC", iso:"ISOlat1"},
		{symbol:"ý", entity:{name:"yacute", code:253}, description:"latin small letter y with acute", unicode:"U+00FD", iso:"ISOlat1"},
		{symbol:"þ", entity:{name:"thorn", code:254}, description:"latin small letter thorn", unicode:"U+00FE", iso:"ISOlat1"},
		{symbol:"ÿ", entity:{name:"yuml", code:255}, description:"latin small letter y with diaeresis", unicode:"U+00FF", iso:"ISOlat1"},
		{symbol:"ƒ", entity:{name:"fnof", code:402}, description:"latin small f with hook = знак функции = florin", unicode:"U+0192", iso:"ISOtech"},
		
		{symbol:"Α", entity:{name:"Alpha", code:913}, description:"греческая заглавная буква альфа", unicode:"U+0391", iso:""},
		{symbol:"Β", entity:{name:"Beta", code:914}, description:"греческая заглавная буква бета", unicode:"U+0392", iso:""},
		{symbol:"Γ", entity:{name:"Gamma", code:915}, description:"греческая заглавная буква гамма", unicode:"U+0393", iso:"ISOgrk3"},
		{symbol:"Δ", entity:{name:"Delta", code:916}, description:"греческая заглавная буква дельта", unicode:"U+0394", iso:"ISOgrk3"},
		{symbol:"Ε", entity:{name:"Epsilon", code:917}, description:"греческая заглавная буква эпсилон", unicode:"U+0395", iso:""},
		{symbol:"Ζ", entity:{name:"Zeta", code:918}, description:"греческая заглавная буква дзета", unicode:"U+0396", iso:""},
		{symbol:"Η", entity:{name:"Eta", code:919}, description:"греческая заглавная буква эта", unicode:"U+0397", iso:""},
		{symbol:"Θ", entity:{name:"Theta", code:920}, description:"греческая заглавная буква тета", unicode:"U+0398", iso:"ISOgrk3"},
		{symbol:"Ι", entity:{name:"Iota", code:921}, description:"греческая заглавная буква иота", unicode:"U+0399", iso:""},
		{symbol:"Κ", entity:{name:"Kappa", code:922}, description:"греческая заглавная буква каппа", unicode:"U+039A", iso:""},
		{symbol:"Λ", entity:{name:"Lambda", code:923}, description:"греческая заглавная буква лямбда", unicode:"U+039B", iso:"ISOgrk3"},
		{symbol:"Μ", entity:{name:"Mu", code:924}, description:"греческая заглавная буква мю", unicode:"U+039C", iso:""},
		{symbol:"Ν", entity:{name:"Nu", code:925}, description:"греческая заглавная буква ню", unicode:"U+039D", iso:""},
		{symbol:"Ξ", entity:{name:"Xi", code:926}, description:"греческая заглавная буква кси", unicode:"U+039E", iso:"ISOgrk3"},
		{symbol:"Ο", entity:{name:"Omicron", code:927}, description:"греческая заглавная буква омикрон", unicode:"U+039F", iso:""},
		{symbol:"Π", entity:{name:"Pi", code:928}, description:"греческая заглавная буква пи", unicode:"U+03A0", iso:"ISOgrk3"},
		{symbol:"Ρ", entity:{name:"Rho", code:929}, description:"греческая заглавная буква ро", unicode:"U+03A1", iso:""},
		{symbol:"Σ", entity:{name:"Sigma", code:931}, description:"греческая заглавная буква сигма", unicode:"U+03A3", iso:"ISOgrk3"},
		{symbol:"Τ", entity:{name:"Tau", code:932}, description:"греческая заглавная буква тау", unicode:"U+03A4", iso:""},
		{symbol:"Υ", entity:{name:"Upsilon", code:933}, description:"греческая заглавная буква ипсилон", unicode:"U+03A5", iso:"ISOgrk3"},
		{symbol:"Φ", entity:{name:"Phi", code:934}, description:"греческая заглавная буква фи", unicode:"U+03A6", iso:"ISOgrk3"},
		{symbol:"Χ", entity:{name:"Chi", code:935}, description:"греческая заглавная буква хи", unicode:"U+03A7", iso:""},
		{symbol:"Ψ", entity:{name:"Psi", code:936}, description:"греческая заглавная буква пси", unicode:"U+03A8", iso:"ISOgrk3"},
		{symbol:"Ω", entity:{name:"Omega", code:937}, description:"греческая заглавная буква омега", unicode:"U+03A9", iso:"ISOgrk3"},
		{symbol:"α", entity:{name:"alpha", code:945}, description:"греческая строчная буква альфа", unicode:"U+03B1", iso:"ISOgrk3"},
		{symbol:"β", entity:{name:"beta", code:946}, description:"греческая строчная буква бета", unicode:"U+03B2", iso:"ISOgrk3"},
		{symbol:"γ", entity:{name:"gamma", code:947}, description:"греческая строчная буква гамма", unicode:"U+03B3", iso:"ISOgrk3"},
		{symbol:"δ", entity:{name:"delta", code:948}, description:"греческая строчная буква дельта", unicode:"U+03B4", iso:"ISOgrk3"},
		{symbol:"ε", entity:{name:"epsilon", code:949}, description:"греческая строчная буква эпсилон", unicode:"U+03B5", iso:"ISOgrk3"},
		{symbol:"ζ", entity:{name:"zeta", code:950}, description:"греческая строчная буква дзета", unicode:"U+03B6", iso:"ISOgrk3"},
		{symbol:"η", entity:{name:"eta", code:951}, description:"греческая строчная буква эта", unicode:"U+03B7", iso:"ISOgrk3"},
		{symbol:"θ", entity:{name:"theta", code:952}, description:"греческая строчная буква тета", unicode:"U+03B8", iso:"ISOgrk3"},
		{symbol:"ι", entity:{name:"iota", code:953}, description:"греческая строчная буква иота", unicode:"U+03B9", iso:"ISOgrk3"},
		{symbol:"κ", entity:{name:"kappa", code:954}, description:"греческая строчная буква каппа", unicode:"U+03BA", iso:"ISOgrk3"},
		{symbol:"λ", entity:{name:"lambda", code:955}, description:"греческая строчная буква лямбда", unicode:"U+03BB", iso:"ISOgrk3"},
		{symbol:"μ", entity:{name:"mu", code:956}, description:"греческая строчная буква мю", unicode:"U+03BC", iso:"ISOgrk3"},
		{symbol:"ν", entity:{name:"nu", code:957}, description:"греческая строчная буква ню", unicode:"U+03BD", iso:"ISOgrk3"},
		{symbol:"ξ", entity:{name:"xi", code:958}, description:"греческая строчная буква кси", unicode:"U+03BE", iso:"ISOgrk3"},
		{symbol:"ο", entity:{name:"omicron", code:959}, description:"греческая строчная буква омикрон", unicode:"U+03BF", iso:"NEW"},
		{symbol:"π", entity:{name:"pi", code:960}, description:"греческая строчная буква пи", unicode:"U+03C0", iso:"ISOgrk3"},
		{symbol:"ρ", entity:{name:"rho", code:961}, description:"греческая строчная буква ро", unicode:"U+03C1", iso:"ISOgrk3"},
		{symbol:"ς", entity:{name:"sigmaf", code:962}, description:"греческая строчная буква сигма (final)", unicode:"U+03C2", iso:"ISOgrk3"},
		{symbol:"σ", entity:{name:"sigma", code:963}, description:"греческая строчная буква сигма", unicode:"U+03C3", iso:"ISOgrk3"},
		{symbol:"τ", entity:{name:"tau", code:964}, description:"греческая строчная буква тау", unicode:"U+03C4", iso:"ISOgrk3"},
		{symbol:"υ", entity:{name:"upsilon", code:965}, description:"греческая строчная буква ипсилон", unicode:"U+03C5", iso:"ISOgrk3"},
		{symbol:"φ", entity:{name:"phi", code:966}, description:"греческая строчная буква фи", unicode:"U+03C6", iso:"ISOgrk3"},
		{symbol:"χ", entity:{name:"chi", code:967}, description:"греческая строчная буква хи", unicode:"U+03C7", iso:"ISOgrk3"},
		{symbol:"ψ", entity:{name:"psi", code:968}, description:"греческая строчная буква пси", unicode:"U+03C8", iso:"ISOgrk3"},
		{symbol:"ω", entity:{name:"omega", code:969}, description:"греческая строчная буква омега", unicode:"U+03C9", iso:"ISOgrk3"},
		{symbol:"ϑ", entity:{name:"thetasym", code:977}, description:"greek small letter theta symbol", unicode:"U+03D1", iso:"NEW"},
		{symbol:"ϒ", entity:{name:"upsih", code:978}, description:"greek upsilon with hook symbol", unicode:"U+03D2", iso:"NEW"},
		{symbol:"ϖ", entity:{name:"piv", code:982}, description:"greek pi symbol", unicode:"U+03D6", iso:"ISOgrk3"},
		
		{symbol:"•", entity:{name:"bull", code:8226}, description:"bullet – маленький черный кружок", unicode:"U+2022", iso:"ISOpub"},
		{symbol:"…", entity:{name:"hellip", code:8230}, description:"многоточие ...", unicode:"U+2026", iso:"ISOpub"},
		{symbol:"′", entity:{name:"prime", code:8242}, description:"одиночный штрих – минуты и футы", unicode:"U+2032", iso:"ISOtech"},
		{symbol:"″", entity:{name:"Prime", code:8243}, description:"двойной штрих – секунды и дюймы", unicode:"U+2033", iso:"ISOtech"},
		{symbol:"‾", entity:{name:"oline", code:8254}, description:"надчеркивание", unicode:"U+203E", iso:"NEW"},
		{symbol:"⁄", entity:{name:"frasl", code:8260}, description:"косая дробная черта", unicode:"U+2044", iso:"NEW"},
		{symbol:"℘", entity:{name:"weierp", code:8472}, description:"рукописное заглавное латинское P – power set – P Вейерштрасса", unicode:"U+2118", iso:"ISOamso"},
		{symbol:"ℑ", entity:{name:"image", code:8465}, description:"blackletter capital I = imaginary part", unicode:"U+2111", iso:"ISOamso"},
		{symbol:"ℜ", entity:{name:"real", code:8476}, description:"blackletter capital R = real part symbol", unicode:"U+211C", iso:"ISOamso"},
		{symbol:"™", entity:{name:"trade", code:8482}, description:"знак торговой марки", unicode:"U+2122", iso:"ISOnum"},
		{symbol:"ℵ", entity:{name:"alefsym", code:8501}, description:"символ алеф – first transfinite cardinal", unicode:"U+2135", iso:"NEW"},
		
		{symbol:"←", entity:{name:"larr", code:8592}, description:"стрелка влево", unicode:"U+2190", iso:"ISOnum"},
		{symbol:"↑", entity:{name:"uarr", code:8593}, description:"стрелка вверх", unicode:"U+2191", iso:"ISOnum"},
		{symbol:"→", entity:{name:"rarr", code:8594}, description:"стрелка вправо", unicode:"U+2192", iso:"ISOnum"},
		{symbol:"↓", entity:{name:"darr", code:8595}, description:"стрелка вниз", unicode:"U+2193", iso:"ISOnum"},
		{symbol:"↔", entity:{name:"harr", code:8596}, description:"стрелка влево-вправо", unicode:"U+2194", iso:"ISOamsa"},
		{symbol:"↵", entity:{name:"crarr", code:8629}, description:"стрелка вниз и влево – знак возврата каретки", unicode:"U+21B5", iso:"NEW"},
		{symbol:"⇐", entity:{name:"lArr", code:8656}, description:"двойная стрелка влево", unicode:"U+21D0", iso:"ISOtech"},
		
		{symbol:"⇑", entity:{name:"uArr", code:8657}, description:"двойная стрелка вверх", unicode:"U+21D1", iso:"ISOamsa"},
		{symbol:"⇒", entity:{name:"rArr", code:8658}, description:"двойная стрелка вправо", unicode:"U+21D2", iso:"ISOtech"},
		{symbol:"⇓", entity:{name:"dArr", code:8659}, description:"двойная стрелка вниз", unicode:"U+21D3", iso:"ISOamsa"},
		{symbol:"⇔", entity:{name:"hArr", code:8660}, description:"двойная стрелка влево-вправо", unicode:"U+21D4", iso:"ISOamsa"},
		{symbol:"∀", entity:{name:"forall", code:8704}, description:"для всех", unicode:"U+2200", iso:"ISOtech"},
		{symbol:"∂", entity:{name:"part", code:8706}, description:"частный дифференциал", unicode:"U+2202", iso:"ISOtech"},
		{symbol:"∃", entity:{name:"exist", code:8707}, description:"существует", unicode:"U+2203", iso:"ISOtech"},
		{symbol:"∅", entity:{name:"empty", code:8709}, description:"пустое множество; диаметр", unicode:"U+2205", iso:"ISOamso"},
		{symbol:"∇", entity:{name:"nabla", code:8711}, description:"набла = backward difference", unicode:"U+2207", iso:"ISOtech"},
		{symbol:"∈", entity:{name:"isin", code:8712}, description:"принадлежит", unicode:"U+2208", iso:"ISOtech"},
		{symbol:"∉", entity:{name:"notin", code:8713}, description:"не принадлежит", unicode:"U+2209", iso:"ISOtech"},
		{symbol:"∋", entity:{name:"ni", code:8715}, description:"содержит", unicode:"U+220B", iso:"ISOtech"},
		{symbol:"∏", entity:{name:"prod", code:8719}, description:"произведение последовательности – знак произведения", unicode:"U+220F", iso:"ISOamsb"},
		{symbol:"∑", entity:{name:"sum", code:8721}, description:"сумма последовательности", unicode:"U+2211", iso:"ISOamsb"},
		{symbol:"−", entity:{name:"minus", code:8722}, description:"минус", unicode:"U+2212", iso:"ISOtech"},
		{symbol:"∗", entity:{name:"lowast", code:8727}, description:"оператор 'звездочка'", unicode:"U+2217", iso:"ISOtech"},
		{symbol:"√", entity:{name:"radic", code:8730}, description:"квадратный корень", unicode:"U+221A", iso:"ISOtech"},
		{symbol:"∝", entity:{name:"prop", code:8733}, description:"пропорционально", unicode:"U+221D", iso:"ISOtech"},
		{symbol:"∞", entity:{name:"infin", code:8734}, description:"бесконечность", unicode:"U+221E", iso:"ISOtech"},
		{symbol:"∠", entity:{name:"ang", code:8736}, description:"угол", unicode:"U+2220", iso:"ISOamso"},
		{symbol:"∧", entity:{name:"and", code:8743}, description:"логическое И – wedge", unicode:"U+2227", iso:"ISOtech"},
		{symbol:"∨", entity:{name:"or", code:8744}, description:"логическое ИЛИ – vee", unicode:"U+2228", iso:"ISOtech"},
		{symbol:"∩", entity:{name:"cap", code:8745}, description:"пересечение – cap", unicode:"U+2229", iso:"ISOtech"},
		{symbol:"∪", entity:{name:"cup", code:8746}, description:"объединение – cup", unicode:"U+222A", iso:"ISOtech"},
		{symbol:"∫", entity:{name:"int", code:8747}, description:"интеграл", unicode:"U+222B", iso:"ISOtech"},
		{symbol:"∴", entity:{name:"there4", code:8756}, description:"следовательно", unicode:"U+2234", iso:"ISOtech"},
		{symbol:"∼", entity:{name:"sim", code:8764}, description:"знак тильда – 'изменяется с' – знак подобия", unicode:"U+223C", iso:"ISOtech"},
		
		{symbol:"≅", entity:{name:"cong", code:8773}, description:"approximately equal to", unicode:"U+2245", iso:"ISOtech"},
		{symbol:"≈", entity:{name:"asymp", code:8776}, description:"почти равно – асимптотически стремится", unicode:"U+2248", iso:"ISOamsr"},
		{symbol:"≠", entity:{name:"ne", code:8800}, description:"не равно", unicode:"U+2260", iso:"ISOtech"},
		{symbol:"≡", entity:{name:"equiv", code:8801}, description:"тождественно", unicode:"U+2261", iso:"ISOtech"},
		{symbol:"≤", entity:{name:"le", code:8804}, description:"меньше либо равно", unicode:"U+2264", iso:"ISOtech"},
		{symbol:"≥", entity:{name:"ge", code:8805}, description:"больше либо равно", unicode:"U+2265", iso:"ISOtech"},
		{symbol:"⊂", entity:{name:"sub", code:8834}, description:"является подмножеством", unicode:"U+2282", iso:"ISOtech"},
		{symbol:"⊃", entity:{name:"sup", code:8835}, description:"является надмножеством", unicode:"U+2283", iso:"ISOtech"},
		{symbol:"⊄", entity:{name:"nsub", code:8836}, description:"не является подмножеством", unicode:"U+2284", iso:"ISOamsn"},
		{symbol:"⊆", entity:{name:"sube", code:8838}, description:"является подмножеством либо равно", unicode:"U+2286", iso:"ISOtech"},
		{symbol:"⊇", entity:{name:"supe", code:8839}, description:"является надмножеством либо равно", unicode:"U+2287", iso:"ISOtech"},
		{symbol:"⊕", entity:{name:"oplus", code:8853}, description:"плюс в кружке – direct sum", unicode:"U+2295", iso:"ISOamsb"},
		{symbol:"⊗", entity:{name:"otimes", code:8855}, description:"знак умножения в кружке – vector product", unicode:"U+2297", iso:"ISOamsb"},
		{symbol:"⊥", entity:{name:"perp", code:8869}, description:"ортогонально, перпендикулярно", unicode:"U+22A5", iso:"ISOtech"},
		{symbol:"⋅", entity:{name:"sdot", code:8901}, description:"оператор 'точка'", unicode:"U+22C5", iso:"ISOamsb"},
		{symbol:"⌈", entity:{name:"lceil", code:8968}, description:"left ceiling = apl upstile", unicode:"U+2308", iso:"ISOamsc"},
		{symbol:"⌉", entity:{name:"rceil", code:8969}, description:"right ceiling", unicode:"U+2309", iso:"ISOamsc"},
		{symbol:"⌊", entity:{name:"lfloor", code:8970}, description:"left floor = apl downstile", unicode:"U+230A", iso:"ISOamsc"},
		{symbol:"⌋", entity:{name:"rfloor", code:8971}, description:"right floor", unicode:"U+230B", iso:"ISOamsc"},
		{symbol:"〈", entity:{name:"lang", code:9001}, description:"левая угловая скобка – bra", unicode:"U+2329", iso:"ISOtech"},
		{symbol:"〉", entity:{name:"rang", code:9002}, description:"правая угловая скобка – ket", unicode:"U+232A", iso:"ISOtech"},
		{symbol:"◊", entity:{name:"loz", code:9674}, description:"lozenge", unicode:"U+25CA", iso:"ISOpub"},
		{symbol:"♠", entity:{name:"spades", code:9824}, description:"черный знак масти 'пики'", unicode:"U+2660", iso:"ISOpub"},
		{symbol:"♣", entity:{name:"clubs", code:9827}, description:"черный знак масти 'трефы' – shamrock", unicode:"U+2663", iso:"ISOpub"},
		{symbol:"♥", entity:{name:"hearts", code:9829}, description:"черный знак масти 'червы' – valentine", unicode:"U+2665", iso:"ISOpub"},
		{symbol:"♦", entity:{name:"diams", code:9830}, description:"черный знак масти 'бубны'", unicode:"U+2666", iso:"ISOpub"},
		{symbol:"\"", entity:{name:"quot", code:34}, description:"двойная кавычка – APL quote", unicode:"U+0022", iso:"ISOnum"},
		{symbol:"&", entity:{name:"amp", code:38}, description:"ampersand", unicode:"U+0026", iso:"ISOnum"},
		{symbol:"<", entity:{name:"lt", code:60}, description:"знак 'меньше'", unicode:"U+003C", iso:"ISOnum"},
		{symbol:">", entity:{name:"gt", code:62}, description:"знак 'больше'", unicode:"U+003E", iso:"ISOnum"},
		{symbol:"Œ", entity:{name:"OElig", code:338}, description:"латинская заглавная лигатура OE", unicode:"U+0152", iso:"ISOlat2"},
		{symbol:"œ", entity:{name:"oelig", code:339}, description:"латинская строчная лигатура oe", unicode:"U+0153", iso:"ISOlat2"},
		{symbol:"Š", entity:{name:"Scaron", code:352}, description:"latin capital letter S with caron", unicode:"U+0160", iso:"ISOlat2"},
		{symbol:"š", entity:{name:"scaron", code:353}, description:"latin small letter s with caron", unicode:"U+0161", iso:"ISOlat2"},
		{symbol:"Ÿ", entity:{name:"Yuml", code:376}, description:"latin capital letter Y with diaeresis", unicode:"U+0178", iso:"ISOlat2"},
		{symbol:"ˆ", entity:{name:"circ", code:710}, description:"modifier letter circumflex accent", unicode:"U+02C6", iso:"ISOpub"},
		{symbol:"˜", entity:{name:"tilde", code:732}, description:"small tilde", unicode:"U+02DC", iso:"ISOdia"},
		{symbol:" ", entity:{name:"ensp", code:8194}, description:"en space", unicode:"U+2002", iso:"ISOpub"},
		{symbol:" ", entity:{name:"emsp", code:8195}, description:"em space", unicode:"U+2003", iso:"ISOpub"},
		{symbol:" ", entity:{name:"thinsp", code:8201}, description:"thin space", unicode:"U+2009", iso:"ISOpub"},
		{symbol:"‌", entity:{name:"zwnj", code:8204}, description:"zero width non-joiner", unicode:"U+200C", iso:"NEW RFC 2070"},
		{symbol:"‍", entity:{name:"zwj", code:8205}, description:"zero width joiner", unicode:"U+200D", iso:"NEW RFC 2070"},
		{symbol:"‎", entity:{name:"lrm", code:8206}, description:"left-to-right mark", unicode:"U+200E", iso:"NEW RFC 2070"},
		{symbol:"‏", entity:{name:"rlm", code:8207}, description:"right-to-left mark", unicode:"U+200F", iso:"NEW RFC 2070"},
		{symbol:"–", entity:{name:"ndash", code:8211}, description:"en dash", unicode:"U+2013", iso:"ISOpub"},
		{symbol:"—", entity:{name:"mdash", code:8212}, description:"em dash", unicode:"U+2014", iso:"ISOpub"},
		{symbol:"‘", entity:{name:"lsquo", code:8216}, description:"левая одиночная кавычка", unicode:"U+2018", iso:"ISOnum"},
		{symbol:"’", entity:{name:"rsquo", code:8217}, description:"правая одиночная кавычка", unicode:"U+2019", iso:"ISOnum"},
		{symbol:"‚", entity:{name:"sbquo", code:8218}, description:"нижняя одиночная кавычка", unicode:"U+201A", iso:"NEW"},
		{symbol:"“", entity:{name:"ldquo", code:8220}, description:"левая двойная кавычка", unicode:"U+201C", iso:"ISOnum"},
		{symbol:"”", entity:{name:"rdquo", code:8221}, description:"правая двойная кавычка", unicode:"U+201D", iso:"ISOnum"},
		{symbol:"„", entity:{name:"bdquo", code:8222}, description:"нижняя двойная кавычка", unicode:"U+201E", iso:"NEW"},
		{symbol:"†", entity:{name:"dagger", code:8224}, description:"кинжал (крест)", unicode:"U+2020", iso:"ISOpub"},
		{symbol:"‡", entity:{name:"Dagger", code:8225}, description:"двойной кинжал (крест)", unicode:"U+2021", iso:"ISOpub"},
		{symbol:"‰", entity:{name:"permil", code:8240}, description:"промилле", unicode:"U+2030", iso:"ISOtech"},
		{symbol:"‹", entity:{name:"lsaquo", code:8249}, description:"левая угловая одиночная кавычка", unicode:"U+2039", iso:"ISO proposed"},
		{symbol:"›", entity:{name:"rsaquo", code:8250}, description:"правая угловая одиночная кавычка", unicode:"U+203A", iso:"ISO proposed"},
		{symbol:"€", entity:{name:"euro", code:8364}, description:"валюта евро", unicode:"U+20AC", iso:"NEW"}
	],
	
	byEntityCode:{},
	byEntityName:{},
	bySymbol:{}
};

(function(){
	function each(coll, F){
		for(var i=0; i<coll.length; i++){
			F(coll[i], i);
		}
	}
	
	function extend(o, s){for(var k in s){o[k] = s[k];}}
	
	var _ = Entities;
	
	each(_.table, function(ent){
		_.byEntityCode[ent.entity.code] = ent;
		_.byEntityName[ent.entity.name] = ent;
		_.bySymbol[ent.symbol] = ent;
		ent.reSymbol = new RegExp(ent.symbol, "g");
		ent.reCode = new RegExp("&#0*"+ent.entity.code+";", "g");
	});
	
	extend(_, {
		replaceAll: function(str){
			str = str.replace(/&(?!(#x?)?[a-z0-9]+;)/g, "&amp;");
			each(_.table, function(ent){
				if(ent.entity.name=="amp")
					return;
				if(!_.enableXmlStdReplacement){
					if(ent.entity.name=="lt" || ent.entity.name=="gt" || ent.entity.name=="quot")
						return;
				}
				var entity = "&"+ent.entity.name+";";
				str = str
					.replace(ent.reSymbol, entity)
					.replace(ent.reCode, entity);
			});
			return str;
		}
	});
})();

