var Entities = {
	table: [
		[symbol:" ", entity:{name:"nbsp", code:160}, description:"неразрывный пробел", unicode:"U+00A0", iso8879Subset:"ISOnum"],
		[symbol:"¡", entity:{name:"iexcl", code:161}, description:"перевернутый восклицательный знак", unicode:"U+00A1", iso8879Subset:"ISOnum"],
		[symbol:"¢", entity:{name:"cent", code:162}, description:"цент", unicode:"U+00A2", iso8879Subset:"ISOnum"],
		[symbol:"£", entity:{name:"pound", code:163}, description:"фунт стерлингов", unicode:"U+00A3", iso8879Subset:"ISOnum"],
		[symbol:"¤", entity:{name:"curren", code:164}, description:"денежная единица", unicode:"U+00A4", iso8879Subset:"ISOnum"],
		[symbol:"¥", entity:{name:"yen", code:165}, description:"иена или юань", unicode:"U+00A5", iso8879Subset:"ISOnum"],
		[symbol:"¦", entity:{name:"brvbar", code:166}, description:"разорванная вертикальная черта", unicode:"U+00A6", iso8879Subset:"ISOnum"],
		[symbol:"§", entity:{name:"sect", code:167}, description:"параграф", unicode:"U+00A7", iso8879Subset:"ISOnum"],
		[symbol:"¨", entity:{name:"uml", code:168}, description:"diaeresis = spacing diaeresis", unicode:"U+00A8", iso8879Subset:"ISOdia"],
		[symbol:"©", entity:{name:"copy", code:169}, description:"знак copyright", unicode:"U+00A9", iso8879Subset:"ISOnum"],
		[symbol:"ª", entity:{name:"ordf", code:170}, description:"feminine ordinal indicator", unicode:"U+00AA", iso8879Subset:"ISOnum"],
		[symbol:"«", entity:{name:"laquo", code:171}, description:"левая двойная угловая скобка", unicode:"U+00AB", iso8879Subset:"ISOnum"],
		[symbol:"¬", entity:{name:"not", code:172}, description:"знак отрицания", unicode:"U+00AC", iso8879Subset:"ISOnum"],
		[symbol:"­", entity:{name:"shy", code:173}, description:"место возможного переноса", unicode:"U+00AD", iso8879Subset:"ISOnum"],
		[symbol:"®", entity:{name:"reg", code:174}, description:"знак зарегистрированной торговой марки", unicode:"U+00AE", iso8879Subset:"ISOnum"],
		[symbol:"¯", entity:{name:"macr", code:175}, description:"macron = spacing macron = overline = APL overbar", unicode:"U+00AF", iso8879Subset:"ISOdia"],
		[symbol:"°", entity:{name:"deg", code:176}, description:"градус", unicode:"U+00B0", iso8879Subset:"ISOnum"],
		[symbol:"±", entity:{name:"plusmn", code:177}, description:"плюс-минус", unicode:"U+00B1", iso8879Subset:"ISOnum"],
		[symbol:"²", entity:{name:"sup2", code:178}, description:"верхний индекс 'два' – 'квадрат'", unicode:"U+00B2", iso8879Subset:"ISOnum"],
		[symbol:"³", entity:{name:"sup3", code:179}, description:"верхний индекс 'три' – 'куб'", unicode:"U+00B3", iso8879Subset:"ISOnum"],
		[symbol:"´", entity:{name:"acute", code:180}, description:"acute accent = spacing acute", unicode:"U+00B4", iso8879Subset:"ISOdia"],
		[symbol:"µ", entity:{name:"micro", code:181}, description:"микро", unicode:"U+00B5", iso8879Subset:"ISOnum"],
		[symbol:"¶", entity:{name:"para", code:182}, description:"pilcrow sign = paragraph sign", unicode:"U+00B6", iso8879Subset:"ISOnum"],
		[symbol:"·", entity:{name:"middot", code:183}, description:"middle dot = Georgian comma = Greek middle dot", unicode:"U+00B7", iso8879Subset:"ISOnum"],
		[symbol:"¸", entity:{name:"cedil", code:184}, description:"cedilla = spacing cedilla", unicode:"U+00B8", iso8879Subset:"ISOdia"],
		[symbol:"¹", entity:{name:"sup1", code:185}, description:"верхний индекс 'один'", unicode:"U+00B9", iso8879Subset:"ISOnum"],
		[symbol:"º", entity:{name:"ordm", code:186}, description:"masculine ordinal indicator", unicode:"U+00BA", iso8879Subset:"ISOnum"],
		[symbol:"»", entity:{name:"raquo", code:187}, description:"правая двойная угловая скобка", unicode:"U+00BB", iso8879Subset:"ISOnum"],
		[symbol:"¼", entity:{name:"frac14", code:188}, description:"дробь – одна четверть", unicode:"U+00BC", iso8879Subset:"ISOnum"],
		[symbol:"½", entity:{name:"frac12", code:189}, description:"дробь – одна вторая", unicode:"U+00BD", iso8879Subset:"ISOnum"],
		[symbol:"¾", entity:{name:"frac34", code:190}, description:"дробь – три четверти", unicode:"U+00BE", iso8879Subset:"ISOnum"],
		[symbol:"¿", entity:{name:"iquest", code:191}, description:"перевернутый вопросительный знак", unicode:"U+00BF", iso8879Subset:"ISOnum"],
		
		[symbol:"À", entity:{name:"Agrave", code:192}, description:"latin capital letter A with grave = latin capital letter A grave", unicode:"U+00C0", iso8879Subset:"ISOlat1"],
		[symbol:"Á", entity:{name:"Aacute", code:193}, description:"latin capital letter A with acute", unicode:"U+00C1", iso8879Subset:"ISOlat1"],
		[symbol:"Â", entity:{name:"Acirc", code:194}, description:"latin capital letter A with circumflex", unicode:"U+00C2", iso8879Subset:"ISOlat1"],
		[symbol:"Ã", entity:{name:"Atilde", code:195}, description:"latin capital letter A with tilde", unicode:"U+00C3", iso8879Subset:"ISOlat1"],
		[symbol:"Ä", entity:{name:"Auml", code:196}, description:"latin capital letter A with diaeresis", unicode:"U+00C4", iso8879Subset:"ISOlat1"],
		[symbol:"Å", entity:{name:"Aring", code:197}, description:"latin capital letter A with ring above = latin capital letter A ring", unicode:"U+00C5", iso8879Subset:"ISOlat1"],
		[symbol:"Æ", entity:{name:"AElig", code:198}, description:"latin capital letter AE = latin capital ligature AE", unicode:"U+00C6", iso8879Subset:"ISOlat1"],
		[symbol:"Ç", entity:{name:"Ccedil", code:199}, description:"latin capital letter C with cedilla", unicode:"U+00C7", iso8879Subset:"ISOlat1"],
		[symbol:"È", entity:{name:"Egrave", code:200}, description:"latin capital letter E with grave", unicode:"U+00C8", iso8879Subset:"ISOlat1"],
		[symbol:"É", entity:{name:"Eacute", code:201}, description:"latin capital letter E with acute", unicode:"U+00C9", iso8879Subset:"ISOlat1"],
		[symbol:"Ê", entity:{name:"Ecirc", code:202}, description:"latin capital letter E with circumflex", unicode:"U+00CA", iso8879Subset:"ISOlat1"],
		[symbol:"Ë", entity:{name:"Euml", code:203}, description:"latin capital letter E with diaeresis", unicode:"U+00CB", iso8879Subset:"ISOlat1"],
		[symbol:"Ì", entity:{name:"Igrave", code:204}, description:"latin capital letter I with grave", unicode:"U+00CC", iso8879Subset:"ISOlat1"],
		[symbol:"Í", entity:{name:"Iacute", code:205}, description:"latin capital letter I with acute", unicode:"U+00CD", iso8879Subset:"ISOlat1"],
		[symbol:"Î", entity:{name:"Icirc", code:206}, description:"latin capital letter I with circumflex", unicode:"U+00CE", iso8879Subset:"ISOlat1"],
		[symbol:"Ï", entity:{name:"Iuml", code:207}, description:"latin capital letter I with diaeresis", unicode:"U+00CF", iso8879Subset:"ISOlat1"],
		//[symbol:"", entity:{name:"", code:162}, description:"", unicode:"U+", iso8879Subset:"ISOlat1"],
		
	]
};
